<a href="https://colab.research.google.com/github/omosehin/TensorFlowBasic/blob/main/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow


In [3]:
import tensorflow as tf
import numpy as np


In [4]:
tf.__version__

'2.4.1'

In [29]:
#Defining a variable in tensor flow 
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)


In [30]:
print("Shape: ", my_variable.shape)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))


Shape:  (2, 2)

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [31]:
my2_tensor = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
my2_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [32]:
my2_tensor.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [33]:
my2_tensor[0,1].assign(90)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 90.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [34]:
my2_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 90.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>